@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Jun 22 21:14:42 +0300 2025
REM SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim Sim_CntNbits_L_behav -key {Behavioral:sim_1:Functional:Sim_CntNbits_L} -tclbatch Sim_CntNbits_L.tcl -protoinst "protoinst_files/bd_95ed.protoinst" -protoinst "protoinst_files/Cnt4bits_ILA_MA.protoinst" -log simulate.log"
call xsim  Sim_CntNbits_L_behav -key {Behavioral:sim_1:Functional:Sim_CntNbits_L} -tclbatch Sim_CntNbits_L.tcl -protoinst "protoinst_files/bd_95ed.protoinst" -protoinst "protoinst_files/Cnt4bits_ILA_MA.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
