# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/temp/Vivado_WorkSpace/Cnt4bits_ILA_MA/Cnt4bits_ILA_MA.srcs/sources_1/bd/Cnt4bits_ILA_MA/ip/Cnt4bits_ILA_MA_clk_wiz_0/Cnt4bits_ILA_MA_clk_wiz_0.xci
# IP: The module: 'Cnt4bits_ILA_MA_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/temp/Vivado_WorkSpace/Cnt4bits_ILA_MA/Cnt4bits_ILA_MA.gen/sources_1/bd/Cnt4bits_ILA_MA/ip/Cnt4bits_ILA_MA_clk_wiz_0/Cnt4bits_ILA_MA_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Cnt4bits_ILA_MA_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/temp/Vivado_WorkSpace/Cnt4bits_ILA_MA/Cnt4bits_ILA_MA.gen/sources_1/bd/Cnt4bits_ILA_MA/ip/Cnt4bits_ILA_MA_clk_wiz_0/Cnt4bits_ILA_MA_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Cnt4bits_ILA_MA_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/temp/Vivado_WorkSpace/Cnt4bits_ILA_MA/Cnt4bits_ILA_MA.gen/sources_1/bd/Cnt4bits_ILA_MA/ip/Cnt4bits_ILA_MA_clk_wiz_0/Cnt4bits_ILA_MA_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Cnt4bits_ILA_MA_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/temp/Vivado_WorkSpace/Cnt4bits_ILA_MA/Cnt4bits_ILA_MA.srcs/sources_1/bd/Cnt4bits_ILA_MA/ip/Cnt4bits_ILA_MA_clk_wiz_0/Cnt4bits_ILA_MA_clk_wiz_0.xci
# IP: The module: 'Cnt4bits_ILA_MA_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/temp/Vivado_WorkSpace/Cnt4bits_ILA_MA/Cnt4bits_ILA_MA.gen/sources_1/bd/Cnt4bits_ILA_MA/ip/Cnt4bits_ILA_MA_clk_wiz_0/Cnt4bits_ILA_MA_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Cnt4bits_ILA_MA_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/temp/Vivado_WorkSpace/Cnt4bits_ILA_MA/Cnt4bits_ILA_MA.gen/sources_1/bd/Cnt4bits_ILA_MA/ip/Cnt4bits_ILA_MA_clk_wiz_0/Cnt4bits_ILA_MA_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Cnt4bits_ILA_MA_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/temp/Vivado_WorkSpace/Cnt4bits_ILA_MA/Cnt4bits_ILA_MA.gen/sources_1/bd/Cnt4bits_ILA_MA/ip/Cnt4bits_ILA_MA_clk_wiz_0/Cnt4bits_ILA_MA_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Cnt4bits_ILA_MA_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
