# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Nexys-A7-100T-Master.xdc

# Block Designs: bd/Cnt4bits_ILA_MA/Cnt4bits_ILA_MA.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cnt4bits_ILA_MA || ORIG_REF_NAME==Cnt4bits_ILA_MA} -quiet] -quiet

# IP: bd/Cnt4bits_ILA_MA/ip/Cnt4bits_ILA_MA_clk_wiz_0/Cnt4bits_ILA_MA_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cnt4bits_ILA_MA_clk_wiz_0 || ORIG_REF_NAME==Cnt4bits_ILA_MA_clk_wiz_0} -quiet] -quiet

# IP: bd/Cnt4bits_ILA_MA/ip/Cnt4bits_ILA_MA_rst_clk_wiz_100M_0/Cnt4bits_ILA_MA_rst_clk_wiz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cnt4bits_ILA_MA_rst_clk_wiz_100M_0 || ORIG_REF_NAME==Cnt4bits_ILA_MA_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/Cnt4bits_ILA_MA/ip/Cnt4bits_ILA_MA_system_ila_0_0/Cnt4bits_ILA_MA_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cnt4bits_ILA_MA_system_ila_0_0 || ORIG_REF_NAME==Cnt4bits_ILA_MA_system_ila_0_0} -quiet] -quiet

# IP: bd/Cnt4bits_ILA_MA/ip/Cnt4bits_ILA_MA_CntNbits_L_MA_0_0/Cnt4bits_ILA_MA_CntNbits_L_MA_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cnt4bits_ILA_MA_CntNbits_L_MA_0_0 || ORIG_REF_NAME==Cnt4bits_ILA_MA_CntNbits_L_MA_0_0} -quiet] -quiet

# IP: bd/Cnt4bits_ILA_MA/ip/Cnt4bits_ILA_MA_Divblock_0_0/Cnt4bits_ILA_MA_Divblock_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cnt4bits_ILA_MA_Divblock_0_0 || ORIG_REF_NAME==Cnt4bits_ILA_MA_Divblock_0_0} -quiet] -quiet

# IP: bd/Cnt4bits_ILA_MA/ip/Cnt4bits_ILA_MA_util_vector_logic_0_0/Cnt4bits_ILA_MA_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cnt4bits_ILA_MA_util_vector_logic_0_0 || ORIG_REF_NAME==Cnt4bits_ILA_MA_util_vector_logic_0_0} -quiet] -quiet

# XDC: c:/Users/EMELNIAP8/Downloads/CntNbits_L_Sim_ILA_MA/CntNbits_L_Sim_ILA_MA/CntNbits_L_Sim_ILA_MA.gen/sources_1/bd/Cnt4bits_ILA_MA/Cnt4bits_ILA_MA_ooc.xdc
